name: build and deploy docs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-docs:
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x.x'
    - name: make script executable
      run: chmod u+x build.sh
    - name: Restore tools
      run: dotnet tool restore
    - name: Build docs
      working-directory: ./
      run: ./build.sh builddocs
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./output/ # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch